# 03. 넘파이

## 넘파이 ndarray 개요

In [1]:
import numpy as np

**ndarray.shape**: ndarray의 shape을 tuple 형식으로 return

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


- array1 array 형태: (3,) -> 1차원 array로 3개의 데이터를 가지고 있음  
- array2 array 형태: (2, 3) -> 2차월 array로 2개의 low와 3개의 col으로 구성되어 $2*3=6$개의 데이터를 가지고 있음  
- array3 array 형태: (1, 3) -> 2차원 array로 1개의 low와 3개의 col으로 구성되어 $1*3=3$개의 데이터를 가지고 있음

**array1과 array3의 차원의 차이를 명확히 이해할 것!**

### 차원 확인

**ndarray.ndim**: ndarray의 차원 **값**을 return

In [4]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


## ndarray의 데이터 타입

ndarray내의 데이터 타입은 그 연산의 특성상 **같은 데이터 타입**만 가능함

**ndarray.dtype**:ndarray내의 데이터타입 return

In [6]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용

In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


**ndarray.astype(<data_type>)**

ndarray 내 데이터값의 타입 변경도 astype() 메서드를 통해 할 수 있음   
주로 메모리 절약을 목적으로 함 (ex. float -> int)

In [8]:
array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)

array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32


In [9]:
array_float1 = np.array([1.1, 2.1, 3.1])
print(array_float1, array_float1.dtype)

array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1.1 2.1 3.1] float64
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones

ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성할 수 있음  
주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화할 때 사용  

**arange(n)**: 0~n까지 값의 ndarray return (start, stop 값을 지정할 수도 있음)

In [11]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


**zeros(<shape=(,)>, <dtype='float64'>)**: 모든 인자가 0인 ndarray return

In [12]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


**ones(<shape=(,)>, <dtype='float64'>)**: 모든 인자가 1인 ndarray return

In [13]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 reshape()

**ndarray.reshape(<shape=(,)>)**

In [14]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

변환할 수 없는 경우 ValueError 발생

-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환됨  
마치 자동 완성!

In [18]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print(array2)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print(array3)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [19]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

마찬가지로, 변환할 수 없는 경우 ValueError 발생

(-1, 1)로 reshape하는 경우, n*1 형태의 ndarray로 변환됨  
stack이나 concat 시 유용함

In [20]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

1. 특정한 데이터만 추출  
2. 슬라이싱(Slicing)
3. 팬시 인덱싱(Fancy Indexing)
4. 불린 인덱싱(Boolean Indexing)

### 1. 단일 값 추출

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


인덱스 -1은 맨 뒤의 데이터값, -2는 맨 뒤에서 두 번째에 있는 데이터값

In [ ]:
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값: 8


단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능함

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


다차원 ndarray에서 단일값을 추출  
1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


하지만, **로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 표현!**  
정확한 표현은 axis 0, axis 1, axis 2, ...

### 2. 슬라이싱

단일 데이터값 추출을 제외 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입으로 return

In [21]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array1)
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


슬라이싱 기호 ':' 사이의 시작, 종료 인덱스는 생략 가능

1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0
2. ':' 기호 위에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스

In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사하며, 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다름

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


n차원 ndarray에서 뒤에 오는 인덱스를 없애면 n-1차원 ndarray를 return

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 3. 팬시 인덱싱

리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 return

In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3= array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4= array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5= array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


### 4. 불린 인덱싱

조건 필터링과 검색을 동시에 할 수 있음

In [ ]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


불린 인덱싱이 동작하는 단계

1. array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재
2. False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장(유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

## 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

**np.sort()**: 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 return  
**ndarray.sort()**: 원 행렬 자체를 정렬한 형태로 return, 반환 값은 None

In [ ]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array, '\n')

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array, '\n')

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5] 

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5] 

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


내림차순으로 정렬하기 위해서는 [::-1]을 적용한다.

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있다.

In [14]:
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향(↓)으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향(→)으로 정렬:\n', sort_array2d_axis1)

로우 방향(↓)으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향(→)으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한다. np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환한다.

In [15]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


내림차순으로 정렬하기 위해서는 [::-1]을 적용한다.

In [17]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [18]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)

두 행렬 A와 B의 내적은 np.dot()울 이용해 계산한다.

In [19]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

np.transpose()를 이용해 계산한다.

In [20]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
